# -*- coding: utf-8 -*-
# ==============================================================================
# == PROFIL RISIKO vFinal - PROJECT CHIMERA ==
# ==============================================================================
#
# Lokasi: CONTROL_PANEL/CONFIG/risk_profile.toml
# Deskripsi: File konfigurasi yang menyimpan semua aturan manajemen risiko
#            dan parameter operasional untuk sistem trading.
#            Versi ini disesuaikan untuk modal awal Rp 1.000.000.
#
# ==============================================================================

# --- 1. BATASAN MODAL & RISIKO HARIAN ---
[capital]
# Modal awal dalam Rupiah (IDR)
initial_balance_idr = 1000000 # Default: 1.000.000 IDR

# Risiko maksimum yang dapat ditanggung per perdagangan (dalam persen dari modal total)
# Contoh: 1.0% berarti risiko maksimal Rp 10.000 per perdagangan
max_risk_per_trade_percent = 1.0 # Default: 1.0%

# Batas maksimum kerugian harian (drawdown) dalam persen dari modal awal
# Contoh: 5.0% berarti sistem akan berhenti jika rugi harian mencapai Rp 50.000
daily_drawdown_limit_percent = 5.0 # Default: 5.0%

# Batas maksimum kerugian mingguan (drawdown) dalam persen dari modal awal
# Contoh: 10.0% berarti sistem akan berhenti jika rugi mingguan mencapai Rp 100.000
weekly_drawdown_limit_percent = 10.0 # Default: 10.0%

# --- 2. UKURAN POSISI & LEVERAGE ---
[position_sizing]
# Metode perhitungan ukuran posisi
# Pilihan: fixed_value | percent_risk | kelly_criterion | volatility_adjusted
method = "percent_risk" # Default: percent_risk

# Nilai tetap ukuran posisi (jika method = fixed_value)
fixed_position_value_idr = 100000 # Default: 100.000 IDR

# Persentase modal dasar yang digunakan per perdagangan (jika method = percent_risk)
# Ini akan disesuaikan oleh manajemen risiko berdasarkan volatilitas dan edge score
base_percentage_per_trade = 1.0 # Default: 1.0%

# Batas minimum nilai posisi (untuk mencegah order terlalu kecil)
minimum_position_value_idr = 50000 # Default: 50.000 IDR

# Batas maksimum nilai posisi (untuk mencegah overexposure)
maximum_position_value_idr = 5000000 # Default: 5.000.000 IDR

# --- 3. MANAJEMEN LEVERAGE ---
[leverage]
# Batas leverage maksimum yang diizinkan
max_allowed_leverage = 10 # Default: 10x

# Leverage default untuk perdagangan
default_leverage = 5 # Default: 5x

# --- 4. STOP-LOSS & TAKE-PROFIT ---
[stop_loss_take_profit]
# Multiplier ATR untuk menentukan jarak stop-loss dinamis
# Contoh: 2.0 berarti stop-loss ditempatkan 2x ATR dari entry price
atr_multiplier_for_stop_loss = 2.0 # Default: 2.0

# Rasio Risk:Reward minimum yang diperlukan untuk membuka posisi
# Contoh: 1:3 berarti potensi profit harus 3x lebih besar dari potensi kerugian
min_risk_reward_ratio = 3.0 # Default: 3.0

# --- 5. PORTOFOLIO & DIVERSIFIKASI ---
[portfolio]
# Jumlah maksimum posisi terbuka simultan
max_open_positions = 5 # Default: 5

# Batas maksimum korelasi antar aset dalam portofolio
# Contoh: 0.7 berarti hindari memiliki 2 aset dengan korelasi > 0.7
max_correlation_between_assets = 0.7 # Default: 0.7

# Wajibkan diversifikasi portofolio?
diversification_required = true # Default: true

# --- 6. PROTEKSI KHUSUS BINANCE ---
[binance_protections]
# Batas ADL Rank Binance (1 = risiko tertinggi)
# Jika posisi Anda memiliki ADL Rank 1, pertimbangkan untuk menutup atau mengurangi ukuran
adl_rank_safety_threshold = 5 # Default: 5

# Penyimpangan harga mark vs harga terakhir yang diizinkan (%)
# Jika >1%, risiko likuidasi palsu meningkat
mark_price_deviation_tolerance_percent = 1.0 # Default: 1.0%

# Batas minimum saldo dana asuransi Binance (BTC)
# Jika <0.5 BTC, risiko socialized loss meningkat
insurance_fund_balance_minimum_btc = 0.5 # Default: 0.5 BTC

# --- 7. MANAJEMEN RISIKO BERDASARKAN VOLATILITAS ---
[volatility_risk_management]
# Periode lookback untuk menghitung ATR (Average True Range)
atr_lookback_period = 14 # Default: 14

# Threshold volatilitas tinggi berdasarkan ATR
# Jika ATR > threshold ini, kurangi ukuran posisi atau hindari perdagangan
high_volatility_atr_threshold = 0.05 # Default: 5% dari harga aset

# --- 8. MANAJEMEN RISIKO BERDASARKAN SENTIMEN ---
[sentiment_risk_management]
# Threshold Fear & Greed Index untuk risiko tinggi
# Jika index <30 (Fear), pertimbangkan risiko lebih tinggi
fear_greed_fear_threshold = 30 # Default: 30

# Threshold Fear & Greed Index untuk euforia berlebihan
# Jika index >70 (Greed), pertimbangkan profit taking atau penurunan leverage
fear_greed_greed_threshold = 70 # Default: 70

# --- 9. MANAJEMEN RISIKO BERDASARKAN EVENT ---
[event_based_risk_management]
# Daftar event berisiko tinggi (dalam format regex atau keyword)
high_risk_events = [
    "FED meeting",
    "CPI release",
    "NFP report",
    "SEC lawsuit",
    "major hack",
    "black swan"
]

# Tindakan otomatis saat event berisiko tinggi terdeteksi
# Pilihan: reduce_leverage | close_positions | hold_only
action_on_high_risk_event = "reduce_leverage" # Default: reduce_leverage

# --- 10. PROTEKSI ANTI-BLOWUP ---
[anti_blowup_protocols]
# Batas drawdown harian yang memicu circuit breaker
circuit_breaker_daily_drawdown_percent = 7.0 # Default: 7.0%

# Tindakan saat circuit breaker dipicu
# Pilihan: halt_trading | reduce_position_size | close_all_positions
circuit_breaker_action = "halt_trading" # Default: halt_trading

# --- AKHIR KONFIGURASI ---